### PR TITLE
fix: load cargo manifest without resolving abs path of deps

### LINKED ISSUE #2016: `Cargo.Bazel.lock` checksum is unstable when using path dependencies in cargo workspace
The `Cargo.Bazel.lock` files produced on mac vs linux are byte-to-byte the same except for the checksum. Could you point me to where this checksum is calculated? Is this expected or a bug? I'm currently using `rules_rust 0.23.0`.

### PR DESCRIPTION
**Pull request by liningpan**
As described in the original issue, `cargo_toml` automatically resolves path dependencies inherited from the cargo workspace to their absolute paths, if the manifest is loaded with  `cargo_toml::Manifest::from_path`. 

The fix I propose here uses the `cargo_toml::Manifest::from_slice`, which does not attempt to load information from the workspace, and dependencies will only show up `Dependency::Inherited` instead of `Dependency::DependencyDetail`.

https://docs.rs/cargo_toml/latest/cargo_toml/struct.Manifest.html#method.from_str
> It does not call `complete_from_path`, so may be missing implicit data.

Even though the documentation says that it may be missing implicit data, it is not a problem for our use case, since the workspace manifest is also loaded and included in the hash. 

fix #2016

### CODE REVIEW

File: crate_universe/src/splicing.rs [hunk 1]
```diff
@@ -118,8 +118,10 @@ impl TryFrom<SplicingManifest> for SplicingMetadata {
             .manifests
             .into_iter()
             .map(|(path, label)| {
-                let manifest = cargo_toml::Manifest::from_path(&path)
+                let manifest_content = fs::read(&path)
```
Comment (UebelAndre) [inline crate_universe/src/splicing.rs:121]: Can you add a comment on the significance of not using `cargo_toml::Manifest::from_path`?

File: crate_universe/src/splicing.rs [hunk 2]
```diff
@@ -582,4 +584,35 @@ mod test {
             PathBuf::from("/tmp/abs/path/workspace/.cargo/config.toml"),
         )
     }
+
+    #[test]
+    fn splicing_metadata_workspace_path() {
```
Comment (UebelAndre) [inline crate_universe/src/splicing.rs:589]: Can you explain how this tests the issue you're seeing? At a glance it seems unrelated.

File: crate_universe/src/splicing.rs [hunk 3]
```diff
@@ -118,9 +118,16 @@ impl TryFrom<SplicingManifest> for SplicingMetadata {
             .manifests
             .into_iter()
             .map(|(path, label)| {
-                let manifest = cargo_toml::Manifest::from_path(&path)
+                // We read the content of a manifest file to buffer and use `from_slice` to
+                // parse it. The reason is that the `from_path` version will resolve indirect
+                // path dependencies in the workspace to absolute path, which causes the hash
+                // to be unstable. Not resolving implicit data is okay here because the
+                // workspace manifest is also included in the hash.
+                // See issue #2016
```
Comment (UebelAndre) [inline crate_universe/src/splicing.rs:126]:
```suggestion
                // See https://github.com/bazelbuild/rules_rust/issues/2016
```

File: crate_universe/src/splicing.rs [hunk 4]
```diff
@@ -582,4 +589,39 @@ mod test {
             PathBuf::from("/tmp/abs/path/workspace/.cargo/config.toml"),
         )
     }
+
+    #[test]
+    fn splicing_metadata_workspace_path() {
+        let runfiles = runfiles::Runfiles::create().unwrap();
+        let workspace_path =
```
Comment (UebelAndre) [inline crate_universe/src/splicing.rs:596]: I think this is undefined behavior with the runfiles API. You should always look for files and then you check for files relative to that. I'd suggest doing something like
```suggestion
        let workspace_manifest_path = runfiles
            .rlocation("rules_rust/crate_universe/test_data/metadata/workspace_path/Cargo.toml");
        let workspace_path = workspace_manifest_path.parent().unwrap();
```

File: crate_universe/src/splicing.rs (hunk 2 above)
Comment (UebelAndre) [reply crate_universe/src/splicing.rs:594]: Awesome! Thank you!

**Review by UebelAndre — CHANGES_REQUESTED** [review]
Looks good! Just one last request 😄

File: crate_universe/src/splicing.rs [hunk 5]
```diff
@@ -582,4 +589,41 @@ mod test {
...
         )
     }
+
+    #[test]
+    fn splicing_metadata_workspace_path() {
+        let runfiles = runfiles::Runfiles::create().unwrap();
+        let workspace_manifest_path = runfiles
+            .rlocation("rules_rust/crate_universe/test_data/metadata/workspace_path/Cargo.toml");
+        let workspace_path = workspace_manifest_path.parent().unwrap();
+        runfiles.rlocation("rules_rust/crate_universe/test_data/metadata/workspace_path");
```
Comment (UebelAndre) [inline crate_universe/src/splicing.rs:599]:
```suggestion
```

File: crate_universe/src/splicing.rs [hunk 6]
```diff
@@ -582,4 +589,41 @@ mod test {
...
+            "rules_rust/crate_universe/test_data/metadata/workspace_path/child_a/Cargo.toml",
+        );
+        let child_b_path = runfiles.rlocation(
+            "rules_rust/crate_universe/test_data/metadata/workspace_path/child_b/Cargo.toml",
+        );
+        let child_b_label = Label::from_str("//child_b:Cargo.toml").unwrap();
+        let manifest = SplicingManifest {
+            direct_packages: BTreeMap::new(),
+            manifests: BTreeMap::from([
+                (parent_path, Label::from_str("//:Cargo.toml").unwrap()),
```
Comment (UebelAndre) [inline crate_universe/src/splicing.rs:612]:
```suggestion
                (workspace_manifest_path, Label::from_str("//:Cargo.toml").unwrap()),
```

**Review by UebelAndre — APPROVED** [review]

File: crate_universe/src/splicing.rs (hunk 6 above)
Comment (liningpan) [reply crate_universe/src/splicing.rs]: Sorry, I didn't look carefully either. This won't compile because `parent()` borrows.
The suggestion ui is really confusing.

Comment (UebelAndre) [reply crate_universe/src/splicing.rs]: No worries! And yeah, it could be better by supporting multi line suggestions. But glad everything is sorted!
